---
- hosts: api
  sudo: yes
  sudo_user: isucon
  gather_facts: no
  tasks:
    - git:
        repo=https://github.com/tagomoris/xbuild.git
        dest=/home/isucon/.xbuild
        update=yes
    # ruby
    - command: /home/isucon/.xbuild/ruby-install 2.2.3 /home/isucon/.local/ruby
      args:
        creates: /home/isucon/.local/ruby/bin/ruby
    # node
    - command: /home/isucon/.xbuild/node-install v4.1.1 /home/isucon/.local/node
      args:
        creates: /home/isucon/.local/node/bin/node
    # python3
    - command: /home/isucon/.xbuild/python-install 3.4.3 /home/isucon/.local/python3
      args:
        creates: /home/isucon/.local/python3/bin/python
    # perl
    - command: /home/isucon/.xbuild/perl-install 5.20.2 /home/isucon/.local/perl
      args:
        creates: /home/isucon/.local/perl/bin/perl
    # php
#    - command: /home/isucon/.xbuild/php-install 7.1.10 /home/isucon/.local/php -- --with-pear --with-openssl
#      args:
#        creates: /home/isucon/.local/php/bin/php
#    - copy: src=../files/php.ini dest=/home/isucon/.local/php/etc/php.ini owner=isucon mode=644
    # golang
    - command: /home/isucon/.xbuild/go-install 1.5 /home/isucon/.local/go
      args:
        creates: /home/isucon/.local/go/bin/go
    # scala
    - shell: curl http://downloads.typesafe.com/scala/2.11.7/scala-2.11.7.tgz | (cd /home/isucon/.local && tar xzf -)
      args:
        creates: /home/isucon/.local/scala-2.11.7/bin/scala
    - file: src=/home/isucon/.local/scala-2.11.7 dest=/home/isucon/.local/scala state=link

- hosts: api
  gather_facts: no
  tasks:
    - apt_repository: repo='ppa:webupd8team/java'
    - name: Autoaccept license for Java8
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
    - apt: name=oracle-java8-installer update_cache=yes
    - apt: name=ca-certificates
    - apt: name=oracle-java8-set-default
    - apt_repository: repo='ppa:cwchien/gradle'
    - apt: name=gradle-3.2.1 update_cache=yes
    - file: src=/usr/lib/jvm/java-8-oracle dest=/usr/lib/jvm/default-java owner=root state=link
